### ISSUE TITLE
question about caa?

### ISSUE THREAD

**Issue by Jialiang14** [twweeb/composite-adv#1]
Hi，thanks for your great job! I have a question about the process of optimizing the order of CAA. Take the rotation as the example, in my opinion, the angle of rotation is larger, the accuracy of model is lower, thus why we need to update each semantic perturbations by gradient descent?

**Comment by twweeb** [comment]
Hi,

Thank you for your question. The reason for using component-wise PGD to update the attack parameter is that we seek to make the optimization suit all scenarios. Based on our observations, some models may only be fooled if the image is rotated by a certain angle. As shown in the figure below, the loss landscape indicates that we can not claim that the greater the rotation degree, the higher the attack success rate. Not to mention that different models may have a variety of loss landscapes for different images. Therefore, using gradient-based optimization is the most efficient one for our problem.

![image](https://user-images.githubusercontent.com/4995599/194000287-c0da07e1-06b0-4b69-b9ac-b943623aa56b.png)
